--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product Home Page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/1/2026 05:53:42
-- Source server version: 5.6.12
-- Source connection string: User Id=root;Host=backapp.localto.net;Port=1790;Database=adminerp;Character Set=utf8
-- Target server version: 5.6.12
-- Target connection string: User Id=root;Host=localhost;Database=adminerp;Character Set=compatibility
-- Run this script against adminerp_copy to synchronize it with adminerp
--

SET NAMES 'utf8';

USE adminerp_copy;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Inserting data into table `bar_detalle_fisico`
--
INSERT INTO bar_detalle_fisico(id, cantidad_unidad, cantidad_detalle, id_producto, id_inventario_fisico, usuario_reg, fecha_reg, fecha_mod, estado) VALUES
(12780, 1.00, 0.00, 36, 501, 'BERNARDO', '2026-01-12', '2026-01-12', 'HAB'),
(12781, 0.00, 0.00, 24, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12782, 0.00, 0.00, 8, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12783, 0.00, 0.00, 139, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12784, 0.00, 0.00, 18, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12785, 0.00, 0.00, 40, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12786, 0.00, 0.00, 48, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12787, 0.00, 0.00, 176, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12788, 0.00, 0.00, 62, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12789, 0.00, 0.00, 60, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12790, 0.00, 0.00, 45, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12791, 0.00, 0.00, 13, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12792, 0.00, 0.00, 65, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12793, 0.00, 0.00, 152, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12794, 0.00, 0.00, 289, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12795, 0.00, 0.00, 174, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12796, 0.00, 0.00, 237, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12797, 0.00, 0.00, 157, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12798, 0.00, 0.00, 306, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12799, 0.00, 0.00, 308, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12800, 0.00, 0.00, 325, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12801, 0.00, 0.00, 459, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12802, 0.00, 0.00, 474, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12803, 0.00, 0.00, 483, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12804, 0.00, 0.00, 210, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB'),
(12805, 0.00, 0.00, 492, 501, 'BERNARDO', '2026-01-12', NULL, 'HAB');

--
-- Inserting data into table `bar_inventario_fisico`
--
INSERT INTO bar_inventario_fisico(id, fecha, observaciones, procesado_por, estado_registro, id_barra, id_operacion, usuario_reg, fecha_reg, fecha_mod, estado) VALUES
(501, '2026-01-12', NULL, 'PRADO LIEVANA, BERNARDO', 62, 1, 1105, 'BERNARDO', '2026-01-12', NULL, 'HAB');

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;