--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/1/2026 21:55:40
-- Server version: 5.6.12
--

INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'nombre', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'p_grupo_categoria', 'int', 'NO', NULL, '', '', 'se define datos como: bebidas, bocaditos, prendas, souvenirs');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'desde', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'hasta', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'correlativo', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_categoria', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'nombre', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'correlativo', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'id_categoria', 'int', 'NO', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'id_proveedor', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'codigo', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'medida', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'p_unidad_medida', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'cantidad_detalle', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'p_unidad_medida_detalle', 'int', 'YES', NULL, '', '', 'kg, oz, etc en parameter_table');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'minimo_stock', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'maximo_stock', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'minimo_stock_barra', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'maximo_stock_barra', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'file', 'mediumblob', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'filename', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'ind_permite_comandar', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'id_barra', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('alm_producto', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'fecha', 'datetime', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id_barra', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id_mesa', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id_operacion', 'int', 'NO', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id_usuario', 'int', 'NO', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'estado_comanda', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'estado_impresion', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'tipo_salida', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'cor_motivo', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'cor_registrado_por', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'razon_social', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'nit', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'id_factura', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'nro_factura', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_comanda', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'nombre', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'codigo', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'id_categoria', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'id_barra', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_combo_coctel', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'cantidad', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id_comanda', 'int', 'NO', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id_producto', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id_salida_combo_coctel', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id_bar_combo_coctel', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'precio_venta', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'sub_total', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'producto_coctel', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'cor_subtotal_anterior', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'id_barra', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'comision', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('bar_detalle_comanda_salida', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id', 'int', 'NO', '0', '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'cantidad', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_comanda', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_producto', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_salida_combo_coctel', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_bar_combo_coctel', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'precio_venta', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'sub_total', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'producto_coctel', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'cor_subtotal_anterior', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_barra', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'fecha_emision', 'datetime', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_operacion', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_mesa', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'razon_social', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'nit', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_factura', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'nro_factura', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'nombre', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'id_producto_combo', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'tipo_salida', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'estado_comanda', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'estado_impresion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('comandas_v6', 'categoria', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'nombre', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'texto1', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'texto2', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'fechaInicio', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'fechaFin', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'numero1', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'numero2', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'id_master', 'int', 'YES', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'orden', 'int', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'requerido', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('parameter_table', 'estado', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'id_producto_combo', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'nombre', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'descripcion', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'categoria', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'id_operacion', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'cantidad_venta', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'precio_venta', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'monto_venta', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'cantidad_cortesia', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('resumen_comandas_ultima_operacion', 'monto_cortesia', 'decimal', 'YES', NULL, '', '', '');