--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/1/2026 19:53:42
-- Server version: 5.6.12
--

SET NAMES 'utf8';

INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'id', 'int', 'NO', NULL, 'PRI', 'auto_increment', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'fecha', 'date', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'nombre_operacion', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'estado_operacion', 'int', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'ind_tiene_cover', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'monto_cover', 'decimal', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'comision', 'decimal', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'id_dia', 'int', 'NO', NULL, 'MUL', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'observaciones', 'varchar', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'usuario_reg', 'varchar', 'NO', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'fecha_reg', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'fecha_mod', 'date', 'YES', NULL, '', '', '');
INSERT INTO information_schema.COLUMNS(TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT) VALUES
('ope_operacion', 'estado', 'varchar', 'NO', NULL, '', '', '');